### ISSUE TITLE
ReactJS로 영화 웹서비스 만들기 강의

### ISSUE THREAD

**Issue by shohom38** [shohom38/react-study#1]
- [x] #2 Basic of React
- [x] #3 STATE
- [x] #4 PROPS
- [x] #5 CREATE REACT APP
- [x] #6 EFFECTS
- [x] #7 PRACTICE MOVIE APP
- [x] Details
